import {
  Activity,
  BillingItem,
  CalendarEvent,
  Case,
  Conversation,
  Document,
} from "../types/types";

export const mockCases: Case[] = [
  {
    id: "1",
    title: "Smith v. Jones Construction",
    caseNumber: "Case #4921",
    client: "John Smith",
    clientInitials: "JS",
    avatarColor: "#3b82f6",
    status: "Active",
    lastActivity: "Today at 10:00 AM",
    hasAvatar: true,
    caseType: "Civil Litigation",
    startDate: "2023-09-15",
    description: "Construction defect case involving residential property",
    assignedTeam: [
      {
        id: "1",
        name: "Jane Doe",
        email: "jane@lawfirm.com",
        role: "Lead Attorney",
      },
      {
        id: "2",
        name: "Mike Ross",
        email: "mike@lawfirm.com",
        role: "Associate",
      },
    ],
  },
  {
    id: "2",
    title: "Estate of A. Doe",
    caseNumber: "Case #4310",
    client: "Jane Doe",
    clientInitials: "JD",
    avatarColor: "#f59e0b",
    status: "Pending",
    lastActivity: "Oct 22, 2023",
    hasAvatar: true,
    caseType: "Estate Planning",
    startDate: "2023-08-10",
    description: "Estate planning and trust administration",
  },
  {
    id: "3",
    title: "TechCorp Merger",
    caseNumber: "Case #5102",
    client: "TechCorp Inc.",
    clientInitials: "TC",
    avatarColor: "#10b981",
    status: "Active",
    lastActivity: "2 hours ago",
    caseType: "Corporate Law",
    startDate: "2023-10-01",
    description: "Merger and acquisition transaction",
  },
  {
    id: "4",
    title: "Martinez Family Trust",
    caseNumber: "Case #4880",
    client: "Robert Martinez",
    clientInitials: "RM",
    avatarColor: "#64748b",
    status: "Closed",
    lastActivity: "Aug 15, 2023",
    hasAvatar: true,
    caseType: "Estate Planning",
    startDate: "2023-06-20",
    description: "Family trust establishment and management",
  },
  {
    id: "5",
    title: "City v. Green Energy",
    caseNumber: "Case #5120",
    client: "Green Energy Sol",
    clientInitials: "GE",
    avatarColor: "#10b981",
    status: "Urgent",
    lastActivity: "Yesterday at 4:30 PM",
    caseType: "Environmental Law",
    startDate: "2023-10-20",
    description: "Environmental compliance dispute",
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "1",
    name: "John Doe",
    initials: "JD",
    avatarColor: "#f59e0b",
    subject: "Re: Smith-Jones Settlement",
    preview:
      "Please review the attached documents regarding the final settlement offer. The...",
    time: "10:42 AM",
    unread: true,
    hasAvatar: true,
    messages: [
      {
        id: "1",
        sender: "user",
        text: "Hi John, I reviewed the settlement offer.",
        time: "10:30 AM",
      },
      {
        id: "2",
        sender: "assistant",
        text: "Please review the attached documents regarding the final settlement offer.",
        time: "10:42 AM",
        attachments: [{ name: "Settlement_Offer.pdf", type: "PDF", pages: 12 }],
      },
    ],
  },
  {
    id: "2",
    name: "Maria Kovac",
    initials: "MK",
    avatarColor: "#a855f7",
    subject: "Court Date Rescheduled",
    preview: "Just a heads up, the judge has moved the hearin...",
    time: "09:15 AM",
    unread: true,
  },
  {
    id: "3",
    name: "Alice Cooper",
    initials: "AC",
    avatarColor: "#64748b",
    subject: "Meeting Confirmation",
    preview: "Thanks, see you on Tuesday at the downtow...",
    time: "Yesterday",
    unread: false,
    hasAvatar: true,
  },
  {
    id: "4",
    name: "Robert Baker",
    initials: "RB",
    avatarColor: "#3b82f6",
    subject: "Billing Inquiry - Invoice #4022",
    preview: "Can we set up a few hours to go over for the...",
    time: "Mon",
    unread: false,
  },
  {
    id: "5",
    name: "David Chen",
    initials: "DC",
    avatarColor: "#64748b",
    subject: "Documents Received",
    preview: "Confirming receipt of the deposition...",
    time: "Last week",
    unread: false,
    hasAvatar: true,
  },
  {
    id: "6",
    name: "Legal Partners LLP",
    initials: "LP",
    avatarColor: "#f59e0b",
    subject: "Partnership Agreement Draft",
    preview: "Attached is the first draft for your revi...",
    time: "2 weeks ago",
    unread: false,
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "1",
    time: "10:00 AM - 11:30 AM",
    title: "Deposition: Smith v. Jones",
    caseNumber: "Case #52-401",
    caseType: "Civil Litigation",
    location: "Conf. Room B",
    attendees: 3,
    type: "deposition",
    color: "#3b82f6",
    priority: "high",
    date: "2023-10-05",
  },
  {
    id: "2",
    time: "1:00 PM - 2:00 PM",
    title: "Client Intake: Michael Ross",
    caseNumber: "Case #53-102",
    caseType: "Corporate Law",
    type: "meeting",
    color: "#10b981",
    date: "2023-10-05",
  },
  {
    id: "3",
    time: "4:00 PM - 5:00 PM",
    title: "Firm Weekly Sync",
    caseNumber: "Internal",
    caseType: "General",
    type: "sync",
    color: "#64748b",
    date: "2023-10-05",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "1",
    type: "document",
    title: "Motion to Dismiss filed",
    description: "Filed motion to dismiss in Smith v. Jones case",
    time: "2 hours ago",
    icon: "document-text",
    iconBg: "#eff6ff",
    iconColor: "#3b82f6",
    caseId: "1",
    caseName: "Smith v. Jones",
    details: {
      fileName: "Motion_to_Dismiss.pdf",
      fileSize: "2.4 MB",
    },
  },
  {
    id: "2",
    type: "payment",
    title: "Payment received",
    description: "Payment received for Estate of Reynolds",
    time: "5 hours ago",
    icon: "card",
    iconBg: "#d1fae5",
    iconColor: "#10b981",
    caseId: "2",
    caseName: "Estate of Reynolds",
    details: {
      amount: "$5,000.00",
    },
  },
  {
    id: "3",
    type: "email",
    title: "Email from opposing counsel",
    description: "Received email regarding TechCorp Litigation",
    time: "Yesterday",
    icon: "mail",
    iconBg: "#f1f5f9",
    iconColor: "#64748b",
    caseId: "3",
    caseName: "TechCorp Litigation",
    details: {
      emailFrom: "counsel@opposingfirm.com",
    },
  },
];

export const mockDocuments: Document[] = [
  {
    id: "1",
    name: "Initial Complaint",
    version: "v1.2",
    date: "Oct 15, 2023",
    type: "Petition",
    icon: "document-text",
    iconBg: "#eff6ff",
    caseId: "1",
  },
  {
    id: "2",
    name: "Evidence Photos",
    version: "Final",
    date: "Oct 12, 2023",
    type: "Evidence",
    icon: "images",
    iconBg: "#fef3c7",
    caseId: "1",
  },
  {
    id: "3",
    name: "Settlement Agreement",
    version: "Draft",
    date: "Oct 10, 2023",
    type: "Contract",
    icon: "document",
    iconBg: "#d1fae5",
    caseId: "1",
  },
];

export const mockBillingItems: BillingItem[] = [
  {
    id: "1",
    type: "unbilled",
    title: "Legal Research - 4.5 hrs",
    date: "Oct 20, 2023",
    status: "Unbilled",
    amount: "$675.00",
    icon: "time",
    iconBg: "#fef3c7",
    caseId: "1",
  },
  {
    id: "2",
    type: "expense",
    title: "Court Filing Fee",
    date: "Oct 18, 2023",
    status: "Pending",
    amount: "$350.00",
    icon: "receipt",
    iconBg: "#eff6ff",
    caseId: "1",
  },
  {
    id: "3",
    type: "paid",
    title: "Consultation - 2 hrs",
    date: "Oct 15, 2023",
    status: "Paid",
    amount: "$500.00",
    icon: "checkmark-circle",
    iconBg: "#d1fae5",
    caseId: "1",
  },
];
